import os
import sys
import re
from google import genai


def extract_block(text: str, start_token: str, end_token: str) -> str | None:
    """
    Extracts content between two marker tokens.
    Example:
      START_OPT_REPORT
      content
      END_OPT_REPORT
    """
    pattern = rf"{re.escape(start_token)}\s*(.*?)\s*{re.escape(end_token)}"
    match = re.search(pattern, text, re.DOTALL)
    return match.group(1).strip() if match else None


def read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_file(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.rstrip() + "\n")


def main() -> None:
    artifact_dir = "./zlib-artifacts"
    optimized_dir = os.path.join(artifact_dir, "optimized")

    os.makedirs(optimized_dir, exist_ok=True)

    report_path = os.path.join(artifact_dir, "CVE-2022-37434.md")
    patch_path = os.path.join(artifact_dir, "flash_patch.diff")
    repro_path = os.path.join(artifact_dir, "repro_cve_2022_37434.c")

    try:
        base_report = read_file(report_path)
        base_patch = read_file(patch_path)
        base_repro = read_file(repro_path)
    except FileNotFoundError as e:
        sys.exit(
            f"Error: {e}\n"
            "Ensure you are running this from the parent directory of 'zlib-artifacts'."
        )

    model_name = os.getenv("GEMINI_MODEL", "gemini-3.1-pro-preview")

    prompt = f"""
You are a Principal Security Engineer and Systems Architect reviewing an automated vulnerability remediation cycle for EdgePatch.

Analyze the base-layer artifacts generated by the junior agent for zlib CVE-2022-37434 and output highly optimized, production-ready iterations.

Context:
- Project: EdgePatch
- Goal: autonomous, air-gapped C/C++ vulnerability validation and remediation
- Vulnerability: zlib CVE-2022-37434
- Desired output: improved engineering report, improved patch, improved reproducer

Optimization Directives:

1. Patch:
Rewrite the nested ternary bounds check to be safe, highly readable, and performant.
Avoid obfuscated structures.
Use idiomatic systems C code.
Preserve the intended semantics of the original fix.
Output a valid unified diff.

2. Reproducer:
Fix all active memory leaks flagged by ASan in the test harness.
Ensure every allocation is freed on all success and error paths.
The reproducer should return 0 when the vulnerability is successfully validated or when the patched version correctly prevents the issue, depending on the report's stated test logic.
Use clear error handling and cleanup labels where appropriate.

3. Report:
Refine the technical details.
Ensure mathematical and logical precision.
Clearly explain:
- root cause
- vulnerable data flow
- exploitability validation method
- patch strategy
- verification result
- limitations

Critical Formatting Rules:

First provide brief architectural commentary.

Then wrap the optimized Markdown report inside:

START_OPT_REPORT
[Your markdown text here]
END_OPT_REPORT

Then wrap the optimized patch file inside:

START_OPT_PATCH
[Your unified diff format patch here]
END_OPT_PATCH

Then wrap the optimized reproducer code inside:

START_OPT_REPRO
[Your complete C code here]
END_OPT_REPRO

Do not omit any of the three tagged sections.

Base Engineering Report:

~~~markdown
{base_report}
~~~

Base Patch:

~~~diff
{base_patch}
~~~

Base Reproducer:

~~~c
{base_repro}
~~~
"""

    client = genai.Client()

    print(f"Calling Gemini model: {model_name}")

    response = client.models.generate_content(
        model=model_name,
        contents=prompt,
    )

    print("Gemini response received.")

    output_text = response.text or ""

    raw_output_path = os.path.join(optimized_dir, "raw_gemini_output.txt")
    write_file(raw_output_path, output_text)

    opt_report = extract_block(output_text, "START_OPT_REPORT", "END_OPT_REPORT")
    opt_patch = extract_block(output_text, "START_OPT_PATCH", "END_OPT_PATCH")
    opt_repro = extract_block(output_text, "START_OPT_REPRO", "END_OPT_REPRO")

    missing = []

    if not opt_report:
        missing.append("optimized report")

    if not opt_patch:
        missing.append("optimized patch")

    if not opt_repro:
        missing.append("optimized reproducer")

    if missing:
        sys.exit(
            "Gemini response was missing required section(s): "
            + ", ".join(missing)
            + f"\nRaw output saved to: {raw_output_path}"
        )

    optimized_report_path = os.path.join(
        optimized_dir,
        "CVE-2022-37434.optimized.md",
    )

    optimized_patch_path = os.path.join(
        optimized_dir,
        "flash_patch.optimized.diff",
    )

    optimized_repro_path = os.path.join(
        optimized_dir,
        "repro_cve_2022_37434.optimized.c",
    )

    write_file(optimized_report_path, opt_report)
    write_file(optimized_patch_path, opt_patch)
    write_file(optimized_repro_path, opt_repro)

    print()
    print("Optimized artifacts written successfully:")
    print(f"  Report:     {optimized_report_path}")
    print(f"  Patch:      {optimized_patch_path}")
    print(f"  Reproducer: {optimized_repro_path}")
    print(f"  Raw output: {raw_output_path}")


if __name__ == "__main__":
    main()